/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

//import BDD.Connexion;
import BDD.Connexion;
import DATA.Client;
import DATA.ClientDemmande;
import DATA.Imprimer;
import DATA.Stock;
import JavaMail.JavaMailUtil;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author hp
 */
public class Homme extends javax.swing.JFrame {
    Connection con;
    Statement st;
    ResultSet re;
    DefaultTableModel table=new DefaultTableModel();
    DefaultTableModel table1=new DefaultTableModel();
    DefaultTableModel table2=new DefaultTableModel();
    DefaultTableModel table3=new DefaultTableModel();
    DefaultTableModel table4=new DefaultTableModel();

//    DefaultTableModel =new DefaultTableModel();
    
    boolean testAdd=false;
    boolean testUPDATE=false;
    boolean testDELETE=false;
    boolean testAddValider=false;
    boolean testAddDeleteValider=false;
    
    /**
     * Creates new form Home1
     */
    public Homme() {
            initComponents();
            setResizable(false);
            table=(DefaultTableModel) Jtable.getModel();
            this.table.setRowCount(0);
            table1=(DefaultTableModel) jTable1.getModel();
            this.table1.setRowCount(0);
            table2=(DefaultTableModel) jTable2.getModel();
            this.table2.setRowCount(0);
            table3=(DefaultTableModel) jTable3.getModel();
            this.table3.setRowCount(0);
            table4=(DefaultTableModel) jTable4.getModel();
            this.table4.setRowCount(0);
            
            int n=getRowNumber();
            total.setText(String.valueOf(n));
        try {
            showTable();
            showTable1();
            showTable4();
        } catch (SQLException ex) {
            Logger.getLogger(Homme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnAjouter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnModification = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        noText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        villeText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        categoryText = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        telText = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        dirigerText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        rech_stock = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnActualiser = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        Vider = new javax.swing.JButton();
        btnImprimer = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnActualiser1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnTerminer = new javax.swing.JButton();
        btnActualiser2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        search_client = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnActualiser3 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        btnActualiser4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N

        jPanel13.setBackground(new java.awt.Color(51, 153, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tout les Droits sont reserve 2021");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(470, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(416, 416, 416))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Bienvenue.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Accueil", new javax.swing.ImageIcon(getClass().getResource("/IMG/home.png")), jPanel1); // NOI18N

        Jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N °", "Dirige par ", "Categorie", "Ville", "Tél", "Disponible"
            }
        ));
        Jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jtable);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));

        btnAjouter.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add2.png"))); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjouterMouseClicked(evt);
            }
        });
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnSupprimer.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/del2.png"))); // NOI18N
        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnModification.setBackground(new java.awt.Color(255, 255, 255));
        btnModification.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnModification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/update2.png"))); // NOI18N
        btnModification.setText("Modifier");
        btnModification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(60, 60, 60)
                .addComponent(btnModification, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(56, 56, 56)
                .addComponent(btnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSupprimer))
                    .addComponent(btnAjouter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)), "Info Véhicules", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 3, 18), new java.awt.Color(0, 204, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel1.setText("N ° d'enregistrement");

        noText.setText("Auto Généré");
        noText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noTextMouseClicked(evt);
            }
        });
        noText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel4.setText("Tél");

        jLabel10.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel10.setText("Ville");

        villeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villeTextActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel11.setText("Catégorie");

        categoryText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambulance - Chambre Simple", "Ambulance - Double Chambre", "Ambulance - Soins Intensifs" }));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel2.setText("(Auto)");

        telText.setColumns(10);
        try {
            telText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel12.setText("Dirigé par");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(categoryText, 0, 174, Short.MAX_VALUE)
                                    .addComponent(villeText)
                                    .addComponent(telText)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(15, 15, 15)
                                .addComponent(noText)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(147, Short.MAX_VALUE)
                    .addComponent(dirigerText, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(villeText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(dirigerText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(138, Short.MAX_VALUE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));

        rech_stock.setEditable(true);
        rech_stock.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                rech_stockPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        rech_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rech_stockActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/rechercher.png"))); // NOI18N

        btnActualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh2.png"))); // NOI18N
        btnActualiser.setText("Actualiser");
        btnActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rech_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualiser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualiser)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rech_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel5.setText("Nombre Total des vehicules:");

        total.setEditable(false);
        total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalMouseClicked(evt);
            }
        });
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        Vider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/if_Remove_27874.png"))); // NOI18N
        Vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViderActionPerformed(evt);
            }
        });

        btnImprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imprimer.png"))); // NOI18N
        btnImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Vider)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnImprimer)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(Vider)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btnImprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Stock Vehicules", new javax.swing.ImageIcon(getClass().getResource("/IMG/stock_car.png")), jPanel2); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N de Vehicule", "CNI", "Localisation", "Date de demmande"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/valider2.png"))); // NOI18N
        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnActualiser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh2.png"))); // NOI18N
        btnActualiser1.setText("Actualiser");
        btnActualiser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(504, 504, 504)
                        .addComponent(jButton1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(491, 491, 491)
                        .addComponent(btnActualiser1)))
                .addContainerGap(369, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnActualiser1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reservation", new javax.swing.ImageIcon(getClass().getResource("/IMG/reserve_liste.png")), jPanel7); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N vehi", "cni client", "nom client", "tele client", "source", "destainataire"
            }
        ));
        jScrollPane4.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        btnTerminer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/arreter.png"))); // NOI18N
        btnTerminer.setText("Terminer");
        btnTerminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminerActionPerformed(evt);
            }
        });

        btnActualiser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh2.png"))); // NOI18N
        btnActualiser2.setText("Actualiser");
        btnActualiser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiser2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(btnTerminer))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(btnActualiser2)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnActualiser2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTerminer)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("En cour d'ex..", new javax.swing.ImageIcon(getClass().getResource("/IMG/execution.png")), jPanel8); // NOI18N

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CNI", "Nom", "Prenom", "Email", "Telephone"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/rechercher.png"))); // NOI18N

        search_client.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                search_clientPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        search_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_clientActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jLabel8.setText("Recherche par le cni ou nom");

        btnActualiser3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh2.png"))); // NOI18N
        btnActualiser3.setText("Actualiser");
        btnActualiser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiser3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_client, 0, 200, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualiser3)
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(search_client, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualiser3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1135, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Les Clients", new javax.swing.ImageIcon(getClass().getResource("/IMG/user1.png")), jPanel3); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/stat3.png"))); // NOI18N
        jButton2.setText("Statéstique par mois");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CNI", "Nom", "Prenom", "Nombre de demmande"
            }
        ));
        jScrollPane2.setViewportView(jTable4);

        btnActualiser4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh2.png"))); // NOI18N
        btnActualiser4.setText("Actualiser");
        btnActualiser4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiser4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(319, 319, 319))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(456, 456, 456))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(btnActualiser4)
                        .addGap(485, 485, 485))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btnActualiser4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Statestique", new javax.swing.ImageIcon(getClass().getResource("/IMG/statistics.png")), jPanel9); // NOI18N

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1116, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void JtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableMouseClicked
                int i=Jtable.getSelectedRow();
//                deplace_info(i);
                TableModel model=Jtable.getModel();
                noText.setText(model.getValueAt(i,0).toString());
                dirigerText.setText(model.getValueAt(i,1).toString());                
                villeText.setText(model.getValueAt(i,3).toString());                
//                    if(model.getValueAt(i,1).toString()==null)
//                       dirigerText.setText("");
//                    else
//                       dirigerText.setText(model.getValueAt(i,1).toString()); 
                String cat=model.getValueAt(i, 2).toString();
                    switch(cat){
                        case "Ambulance - Chambre Simple":
                            categoryText.setSelectedIndex(0);
                            break;
                        case "Ambulance - Double Chambre":
                            categoryText.setSelectedIndex(1);
                            break;
                        case "Ambulance - Soins Intensifs":
                            categoryText.setSelectedIndex(2);
                            break;
                    }
                telText.setText(model.getValueAt(i,4).toString());
    }//GEN-LAST:event_JtableMouseClicked
    public void setStock(){
        
        String no=noText.getText();
        String diriger=dirigerText.getText();
        String ville=villeText.getText();
        String category=categoryText.getSelectedItem().toString();        
        String tele=telText.getText(); 
        System.out.println("ttttttttttt "+tele);
        String status="Oui";
        Stock s=new Stock(no, diriger, category, ville,tele, status);
//        System.out.println(s.toString());


        if(btnAjouter.getModel().isArmed()){
            testAdd=s.ajouter();
//            System.out.println("btn ajouttttttttttter");
        }
            
        if(btnModification.getModel().isArmed()){
            testUPDATE=s.modifier();
//            System.out.println("btn suuuuuuuuuuuuuuuuuuuuuuuuuprimer");
        }
        if(btnSupprimer.getModel().isArmed()){
            testDELETE=s.supprimer();
//            System.out.println("btn suuuuuuuuuuuuuuuuuuuuuuuuuprimer");
        }
        
        
            
    }
    
    
    
    public void showTable() throws SQLException{
        table.setRowCount(0);//pour vider Jtable avant le remplssage , bax mayb9ax est afficher omnb3d ajout i3awd est afficher mn lawal
        String req2="select * from stock";
        con=Connexion.connecterDB();
        st=con.createStatement();
        try {
            re=st.executeQuery(req2);
            while(re.next()){//si resultset tat ji 3la objet bzaf dyl les lignes boucler doz mn str str next next 
                String t[]=new String[]{re.getString("NO"),re.getString("MANAGEDBY"),re.getString("CATEGORY"),re.getString("ville"),re.getString("PHONE"),re.getString("STATUS")};
                table.addRow(t);//had str dyl t table ghan zidoh defaulttablemodel ,hadxi ayb9a ytzad fkola str kayn resultSet
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"erreur: "+ex.toString());
            
        }
        int n=getRowNumber();
            total.setText(String.valueOf(n));
    }
    public void showTable1() throws SQLException{
        table1.setRowCount(0);//pour vider Jtable avant le remplssage , bax mayb9ax est afficher omnb3d ajout i3awd est afficher mn lawal
        String req2="select * from valider";
        con=Connexion.connecterDB();
        st=con.createStatement();
        try {
            re=st.executeQuery(req2);
            while(re.next()){//madam resultset tat ji 3la objet bzaf dyl les lignes boucler doz mn str str next next 
                String t[]=new String[]{re.getString("n"),re.getString("cni"),re.getString("nom"),re.getString("tele"),re.getString("src"),re.getString("dest")};
                table1.addRow(t);//had str dyl t table ghan zidoh defaulttablemodel ,hadxi ayb9a ytzad fkola str kayn resultSet
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"erreur: "+ex.toString());
            
        }
        int n=getRowNumber();
            total.setText(String.valueOf(n));
    }
    public void showTable2() throws SQLException{
        table2.setRowCount(0);//pour vider Jtable avant le remplssage , bax mayb9ax est afficher omnb3d ajout i3awd est afficher mn lawal
        String req2="select * from demmande";
        con=Connexion.connecterDB();
        st=con.createStatement();
        try {
            re=st.executeQuery(req2);
            while(re.next()){//madam resultset tat ji 3la objet bzaf dyl les lignes boucler doz mn str str next next 
                String t[]=new String[]{re.getString("NUmeroV"),re.getString("CNI"),re.getString("LOCALISATION"),re.getString("DATEDEM")};
                table2.addRow(t);//had str dyl t table ghan zidoh defaulttablemodel ,hadxi ayb9a ytzad fkola str kayn resultSet
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"erreur: "+ex.toString());
            
        }
        int n=getRowNumber();
            total.setText(String.valueOf(n));
    }
    public void showTable3() throws SQLException{
        table3.setRowCount(0);
                String req="select cni,nom,prenom,email,tele from insc";
        con=Connexion.connecterDB();
        st=con.createStatement();
        try{
            re=st.executeQuery(req);
            while(re.next()){
                String t[]=new String[]{
                    re.getString("cni"),re.getString("nom"),re.getString("prenom"),re.getString("email"),re.getString("tele")};
                    table3.addRow(t);
                }
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"erreur: "+ex.toString());    
        }
    }
    public void showTable4() throws SQLException{
        table4.setRowCount(0);
                String req="select cni,nom,prenom,nmbrdemmande from insc order by nmbrdemmande desc";
        con=Connexion.connecterDB();
        st=con.createStatement();
        try{
            re=st.executeQuery(req);
            while(re.next()){
                String t[]=new String[]{
                    re.getString("cni"),re.getString("nom"),re.getString("prenom"),re.getString("nmbrdemmande")};
                    table4.addRow(t);
                }
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"erreur: "+ex.toString());    
        }
    }
    String getKey(){
        String s=null;
        Random r=new Random();
//        int v=r.nextInt(100000);
        int v=(int)(Math.random()*998+100);//entre 100 et 999
        char c=(char)(r.nextInt(26)+'A');
        s="VH"+""+v+""+c;
        return s;
    }
    
    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        try {
            setStock();
            if(testAdd){
                JOptionPane.showMessageDialog(null,"L'ajout est bient faits");
                showTable();
                noText.setText(getKey());
                dirigerText.setText("");
                villeText.setText("");
                telText.setText("");
            }
            else{
                JOptionPane.showConfirmDialog(null,"Erreur d'ajout");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Homme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        
            
            try {
            int n=JOptionPane.showConfirmDialog(null, "voulez-vous continuer ?");
            if(n==0){
            setStock();
            if(testDELETE){
                JOptionPane.showMessageDialog(null,"Supprimer est bien fait");
                showTable();
                noText.setText(getKey());
                
                villeText.setText("");
                dirigerText.setText("");
                telText.setText("");
            }
            else{
                JOptionPane.showConfirmDialog(null,"Erreur supprimer");
            } 
           }
        } catch (SQLException ex) {
            Logger.getLogger(Homme.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnModificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificationActionPerformed

                try{
//                        setStockUpdate();
                        setStock();
                        
//                        c1.setId(new Double(noText.getText()).intValue());//dik text tat rad string dik xi lax drna casting
                        if(testUPDATE){
                                JOptionPane.showMessageDialog(null,"le mise a jour est success");
                                showTable();
                            }
                                    else{
                                        JOptionPane.showConfirmDialog(null,"Erreur mise a jour");
                                        }
                    }catch (Exception e){
                        JOptionPane.showConfirmDialog(null,"Erreur "+e.toString());
                        e.printStackTrace();
                    }
    }//GEN-LAST:event_btnModificationActionPerformed

    private void noTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTextActionPerformed

    private void noTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noTextMouseClicked
        noText.setText(getKey());
    }//GEN-LAST:event_noTextMouseClicked

    private void btnAjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjouterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjouterMouseClicked
    public void filter_stock(JComboBox c){
        try {
//            Connexion.Setconnection();
//            Connexion.connecterDB();
            c.removeAllItems();
            AutoCompleteDecorator.decorate(c);
            //setconnection
            con=Connexion.connecterDB();
            Statement stm=con.createStatement();
            String s="select * from stock";
            ResultSet r=stm.executeQuery(s);
            while(r.next()){
                c.addItem(""+r.getString(1));
                c.addItem(""+r.getString(2));
            }
            c.setSelectedItem("");
            con.close();
       } catch (SQLException e) {
        }
    }
    //pour voir les donnees dans le ComboBox
    public void filter_client(JComboBox c){
        try {
//            Connexion.Setconnection();
//            Connexion.connecterDB();
            c.removeAllItems();
            AutoCompleteDecorator.decorate(c);
            //setconnection
            con=Connexion.connecterDB();
            Statement stm=con.createStatement();
            String s="select * from insc";
            ResultSet r=stm.executeQuery(s);
            while(r.next()){
                c.addItem(""+r.getString(1));
                c.addItem(""+r.getString(2));
            }
            c.setSelectedItem("");
            con.close();
       } catch (SQLException e) {
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        filter_stock(rech_stock);
        filter_client(search_client);
    }//GEN-LAST:event_formWindowOpened

    private void rech_stockPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_rech_stockPopupMenuWillBecomeInvisible
    
        try {
            table.setRowCount(0);
            String nom=(String) rech_stock.getSelectedItem();
            con=Connexion.connecterDB();
            Statement stm=con.createStatement();
            
            String s="select * from stock where no='"+nom+"' or managedby='"+nom+"'";
            ResultSet r=stm.executeQuery(s);
            while(r.next()){
                Object[] model={r.getString(1),r.getString(2),r.getString(3),r.getString(6),r.getString(4),r.getString(5)};
                table.addRow(model);
            }
            
            con.close();
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_rech_stockPopupMenuWillBecomeInvisible

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        
    }//GEN-LAST:event_totalActionPerformed
        public int getRowNumber(){
            int numberRow = 0;
        try {
            con=Connexion.connecterDB();
            Statement stm=con.createStatement();
            
            String s="select count(*) from stock";
            ResultSet r=stm.executeQuery(s);
            while(r.next()){    
                numberRow=r.getInt("count(*)");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Homme.class.getName()).log(Level.SEVERE, null, ex);
        }    
        return numberRow;
        }
        
    private void totalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalMouseClicked

//        int n=getRowNumber();
//        total.setText(String.valueOf(n));
//System.out.println(getRowNumber());
    }//GEN-LAST:event_totalMouseClicked

    private void ViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViderActionPerformed
        
        Stock s=new Stock();
        int n=JOptionPane.showConfirmDialog(null,"Supprimer tous ??");
        // 0=yes, 1=no, 2=cancel
        if(n==0){
            if(s.supprimerTous())
                JOptionPane.showMessageDialog(null,"Bien Vider");
            else 
                JOptionPane.showMessageDialog(null,"Erreur de vider");
        }
        
    }//GEN-LAST:event_ViderActionPerformed

    private void villeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_villeTextActionPerformed
    public void getInfo(){
                int i=jTable2.getSelectedRow();
                TableModel model1=jTable2.getModel();
        String no=model1.getValueAt(i,0).toString();
        String cni=model1.getValueAt(i,1).toString();
        String email=new Client().getEmail(cni);
//        System.out.println("haaaaaaaaaaaa "+email);
        ClientDemmande d=new ClientDemmande();
        d.setCni(cni);
        d.setNumeroV(no);
        testAddValider=d.ajouterValider();
        
        //send email
        if(testAddValider)
            JavaMailUtil.sendMail(email);
            
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getInfo();
        if (testAddValider) {
            JOptionPane.showMessageDialog(this, "Validation est bien effectuer");
        } else {
            JOptionPane.showMessageDialog(this, "Validation est refusee", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTerminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminerActionPerformed
        int i=jTable1.getSelectedRow();
        TableModel model2=jTable1.getModel();
        String no=model2.getValueAt(i,0).toString();
        ClientDemmande l=new ClientDemmande();
        System.out.println("kaaaaaaaaaaalaaaaaaaaaa :"+no);
        l.setNumeroV(no);
        System.out.println("kaaaaaaaaaaalaaaaaaaaaa f get :"+l.getNumeroV());
        testAddDeleteValider=l.supprimerValider();
        if(testAddDeleteValider){
            JOptionPane.showMessageDialog(this, "L'operation bien effectuer");
        }else{
            JOptionPane.showMessageDialog(this, "L'operation est refusee", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTerminerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        XYSeries s=new XYSeries("data");
        DATA.Get x=new DATA.Get();
        try{
            s.add(1,x.Janvier());
            s.add(2,x.Fevrier());
            s.add(3,x.Mars());
            s.add(4,x.Avril());
            s.add(5,x.Mai());
            s.add(6,x.Juin());
            s.add(7,x.Juillet());
            s.add(8,x.Aout());
            s.add(9,x.Septembre());
            s.add(10,x.Octobre());
            s.add(11,x.Novembre());
            s.add(12,x.Decembre());
        }catch(Exception e){
            e.printStackTrace();
        }
        
        XYSeriesCollection datest=new XYSeriesCollection(s);
        JFreeChart ch=ChartFactory.createXYBarChart("Les domandes par mois", "Les Mois",false,"Le nombre des demandes",datest,PlotOrientation.VERTICAL,false,false,false);
        ChartFrame frame=new ChartFrame("Statestiques", ch);
        frame.pack();
        frame.setVisible(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rech_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rech_stockActionPerformed
        
    }//GEN-LAST:event_rech_stockActionPerformed

    private void search_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_clientActionPerformed
        
    }//GEN-LAST:event_search_clientActionPerformed

    private void search_clientPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_search_clientPopupMenuWillBecomeInvisible
        try {
            table3.setRowCount(0);
            String nom=(String) search_client.getSelectedItem();
            con=Connexion.connecterDB();
            Statement stm=con.createStatement();
            
            String s="select cni,nom,prenom,email,tele from insc where cni='"+nom+"' or nom='"+nom+"'";
            ResultSet r=stm.executeQuery(s);
            while(r.next()){
                Object[] model={r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5)};
                table3.addRow(model);
            }
            
            con.close();
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_search_clientPopupMenuWillBecomeInvisible

    private void btnImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimerActionPerformed
        String titre="Liste des vehicules";
        Imprimer.imprimerJtable(Jtable, titre);
    }//GEN-LAST:event_btnImprimerActionPerformed

    private void btnActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiserActionPerformed
         try {
            showTable();
        } catch (SQLException ex) {
            Logger.getLogger(Homme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualiserActionPerformed

    private void btnActualiser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiser1ActionPerformed
        try {
            showTable2();
        } catch (SQLException ex) {
            Logger.getLogger(Homme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualiser1ActionPerformed

    private void btnActualiser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiser2ActionPerformed
       try {
            showTable1();
        } catch (SQLException ex) {
            Logger.getLogger(Homme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualiser2ActionPerformed

    private void btnActualiser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiser3ActionPerformed
       try {
            showTable3();
        } catch (SQLException ex) {
            Logger.getLogger(Homme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualiser3ActionPerformed

    private void btnActualiser4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiser4ActionPerformed
       try {
            showTable4();
        } catch (SQLException ex) {
            Logger.getLogger(Homme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualiser4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            //here you can put the selected theme class name in JTattoo
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            

        }  catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtable;
    private javax.swing.JButton Vider;
    private javax.swing.JButton btnActualiser;
    private javax.swing.JButton btnActualiser1;
    private javax.swing.JButton btnActualiser2;
    private javax.swing.JButton btnActualiser3;
    private javax.swing.JButton btnActualiser4;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnImprimer;
    private javax.swing.JButton btnModification;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnTerminer;
    private javax.swing.JComboBox<String> categoryText;
    private javax.swing.JTextField dirigerText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField noText;
    private javax.swing.JComboBox<String> rech_stock;
    private javax.swing.JComboBox<String> search_client;
    private javax.swing.JFormattedTextField telText;
    private javax.swing.JTextField total;
    private javax.swing.JTextField villeText;
    // End of variables declaration//GEN-END:variables

    
  
}
